# Part-1 Basic ML
## Lab-01-1 Tensor Manipulation 1
- 텐서(Tensor)
- 넘파이(NumPy)
- 텐서 조작(Tensor Manipulation)
- 브로드캐스팅(Broadcasting)

### Tensor
- 2D Tensor: $|t| = (batch size, \ dim)$
- 3D Tensor: $|t| = (batch size, \ width, \ height)$ (vision)
- 3D Tensor: $|t| = (batch size, \ length, \ dim)$ (NLP, Seq.)

In [1]:
import torch
import numpy as np

#### 1D Array with NumPy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print(f"Rank of t: {t.ndim}")
print(f"Shape of t: {t.shape}")

Rank of t: 1
Shape of t: (7,)


In [4]:
# Element
print(t[0], t[1], t[-1])
# Slicing
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


#### 2D Array with NumPy

In [5]:
t = np.array(
    [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.],
     [10., 11., 12.]]
)

print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print(f"Rank of t: {t.ndim}")
print(f"Shape of t: {t.shape}")

Rank of t: 2
Shape of t: (4, 3)


#### 1D Array with PyTorch

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
# Rank
print(f"Rank: {t.dim()}")
# Shape
print(f"Shape: {t.shape}")
print(f"Shape: {t.size()}")
# Element
print(t[0], t[1], t[-1])
# Slicing
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

Rank: 1
Shape: torch.Size([7])
Shape: torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


#### 2D Array with PyTorch

In [9]:
t = torch.FloatTensor(
    [[1., 2., 3.],
     [4., 5., 6.],
     [7., 8., 9.],
     [10., 11., 12.]]
)

print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
# Rank
print(f"Rank: {t.dim()}")
# Shape
print(t.size())
# Slicing
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

Rank: 2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting
다른 크기의 행렬을 연산 할 때 적용되는 기능

In [12]:
# same shape
m1 = torch.FloatTensor([[3, 3]]) # (1, 2)
m2 = torch.FloatTensor([[2, 2]]) # (1, 2)

print(m1.shape, m2.shape)
print(m1+m2)

torch.Size([1, 2]) torch.Size([1, 2])
tensor([[5., 5.]])


In [13]:
# Vec + scaler
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])

print(m1.shape, m2.shape)
print(m1+m2)

torch.Size([1, 2]) torch.Size([1])
tensor([[4., 5.]])


In [14]:
# 2*1 vec + 1*2 vec
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])

print(m1.shape, m2.shape)
print(m1+m2)

torch.Size([1, 2]) torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


$$
\begin{bmatrix}
1 & 2
\end{bmatrix}
+
\begin{bmatrix}
3 \\
4
\end{bmatrix}
=
\begin{bmatrix}
1 & 2 \\
1 & 2
\end{bmatrix}
+
\begin{bmatrix}
3 & 3 \\
4 & 4
\end{bmatrix}
=
\begin{bmatrix}
4 & 5 \\
5 & 6
\end{bmatrix}
$$

### Multiplication vs Matrix Multiplication
- 딥러닝은 행렬곱을 굉장히 많이 사용하는 알고리즘

In [18]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print(f"Shape of Matrix 1: {m1.shape}") # 2 x 2
print(f"Shape of Matrix 2: {m2.shape}") # 2 x 1

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])


In [22]:
print(m1)
print("-"*10)
print(m2)

tensor([[1., 2.],
        [3., 4.]])
----------
tensor([[1.],
        [2.]])


In [19]:
m1.matmul(m2)

tensor([[ 5.],
        [11.]])

In [23]:
m1*m2

tensor([[1., 2.],
        [6., 8.]])

#### !!NOTE!!
- `np.matmul(a, b)` == `a@b`: 2D의 행렬곱
- `np.dot(a, b)`:
  - 1D의 내적
  - 2D의 행렬곱
  - nD의 경우, 첫 행렬의 마지막 축과 두 번째 행렬의 -2번째 축의 내적

In [24]:
a = np.array(
    [[1, 2],
     [3, 4]]
)

b = np.array(
    [[1, 2],
     [3, 4]]
)

In [27]:
np.matmul(a, b)

array([[ 7, 10],
       [15, 22]])

In [26]:
np.dot(a, b)

array([[ 7, 10],
       [15, 22]])

In [28]:
# point-wise
a*b

array([[ 1,  4],
       [ 9, 16]])

In [29]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])

In [32]:
np.matmul(a, b), np.dot(a, b)

(14, 14)

In [33]:
a*b

array([1, 4, 9])

### Mean

In [36]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [38]:
t = torch.LongTensor([1, 2])
try: print(t.mean())
except Exception as e:
    print(e)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


평균(Mean)은 정수형 텐서로는 못구함

In [39]:
t = torch.FloatTensor(
    [[1, 2],
     [3, 4]]
)
print(t)

tensor([[1., 2.],
        [3., 4.]])
